//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectumCareerNightBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DirectumCareerNightBot.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналитика 🦉.
        /// </summary>
        internal static string Analitycs {
            get {
                return ResourceManager.GetString("Analitycs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋 *Привет, это команда Directum\!*
        ///
        ///36 лет мы создаём решения, которые упрощают электронный документооборот, бизнес\-процессы и жизнь в целом\.
        ///
        ///Этот чат\-бот был создан специально для Ночи карьеры\. ✨ *С его помощью ты сможешь попасть на собеседование, узнать о направлениях работ в компании, получить мерч и откликнуться на практику\.*✨
        ///
        ///Поехали\!🚀
        ///        .
        /// </summary>
        internal static string BotStartMessage {
            get {
                return ResourceManager.GetString("BotStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать о вакансиях.
        /// </summary>
        internal static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнать о направлениях работ.
        /// </summary>
        internal static string Directum15Questions {
            get {
                return ResourceManager.GetString("Directum15Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания Directum в VK.
        /// </summary>
        internal static string DirectumCompanyVK {
            get {
                return ResourceManager.GetString("DirectumCompanyVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенты Directum в VK.
        /// </summary>
        internal static string DirectumStudentsVK {
            get {
                return ResourceManager.GetString("DirectumStudentsVK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ⚡*Поднимайся на сцену\! За столом с табличкой «Попасть в ИТ» тебе расскажут о возможностях\.⚡* Крепись, ты можешь оказаться 30\-м в очереди на общение\.
        ///А  пока есть время, и ты уже занял очередь, можешь прогуляться к нашему стенду🍊\.
        ///
        ///Команда Directum подготовила список вакансий, которые могут тебе подойти\. Переходи [по ссылке](https://career.directum.ru/)\, а также подписывайся на нашу группу, чтобы первым узнавать об актуальной практике и новых вакансиях\..
        /// </summary>
        internal static string GoUpInIT {
            get {
                return ResourceManager.GetString("GoUpInIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как удобнее будет поддерживать связь с нашим HR\-ом — *напиши свои телефон/почту/vk*.
        /// </summary>
        internal static string HowToContact {
            get {
                return ResourceManager.GetString("HowToContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбери направление, которое тебе интересно, или напиши свой вариант.
        /// </summary>
        internal static string InterestingDirection {
            get {
                return ResourceManager.GetString("InterestingDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Давай знакомиться, *напиши свои фамилию, имя и отчество*.
        /// </summary>
        internal static string IntroduceYourself {
            get {
                return ResourceManager.GetString("IntroduceYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбирай, что тебе интересно\!.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуться в меню 🔙.
        /// </summary>
        internal static string MainMenuButton {
            get {
                return ResourceManager.GetString("MainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Маркетинг 📢.
        /// </summary>
        internal static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я уже не студент 😎.
        /// </summary>
        internal static string NotStudent {
            get {
                return ResourceManager.GetString("NotStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сейчас Directum готов принимать опытных специалистов, и такие есть среди участников Ночи карьеры\. 
        ///А ещё мы знаем пути вхождения в ИТ и готовы делиться ими со всеми желающими\.
        ///Выбери, что тебе интересно:
        ///.
        /// </summary>
        internal static string NotStudentMessage {
            get {
                return ResourceManager.GetString("NotStudentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработка 🕸️.
        /// </summary>
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прикольный квиз от Егора.
        /// </summary>
        internal static string Quiz {
            get {
                return ResourceManager.GetString("Quiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🎁*Ответь верно на 5 вопросов и получи подарок от Directum\!*.
        /// </summary>
        internal static string QuizStartMessage {
            get {
                return ResourceManager.GetString("QuizStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продажи и Маркетинг 💰.
        /// </summary>
        internal static string SailsAndMarketing {
            get {
                return ResourceManager.GetString("SailsAndMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Я студент 🤓.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡*Да, в Directum можно работать со студенчества\.*⚡ 
        ///У нас можно пройти летнюю практику, *работать по 4 или 8 часов в день\.* И самое главное развиваться\.
        ///Чего хочешь ты?
        ///        .
        /// </summary>
        internal static string StudentMessage {
            get {
                return ResourceManager.GetString("StudentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На работу!.
        /// </summary>
        internal static string StudentWithExperience {
            get {
                return ResourceManager.GetString("StudentWithExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инженерная поддержка, DevOps, администратор 🙏.
        /// </summary>
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тех. документация 🖋️.
        /// </summary>
        internal static string TechDoc {
            get {
                return ResourceManager.GetString("TechDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи про свой опыт в этом направлении.
        /// </summary>
        internal static string TellAboutChosenDirection {
            get {
                return ResourceManager.GetString("TellAboutChosenDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи о своём опыте в IT, в какой компании работал, на какой должности.
        /// </summary>
        internal static string TellAboutITExpirience {
            get {
                return ResourceManager.GetString("TellAboutITExpirience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи о своём последнем месте работы, опыте.
        /// </summary>
        internal static string TellAboutLastWork {
            get {
                return ResourceManager.GetString("TellAboutLastWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи в какой компании работаешь, на какой должности, кратко опиши свои задачи.
        /// </summary>
        internal static string TellAboutYourCompany {
            get {
                return ResourceManager.GetString("TellAboutYourCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расскажи какие задачи ты выполняешь на своей должности.
        /// </summary>
        internal static string TellAboutYourCompanyPlace {
            get {
                return ResourceManager.GetString("TellAboutYourCompanyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестирование 🐞.
        /// </summary>
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡*Поднимайся на сцену\. За столом с табличкой «Есть контакт\. Тестирование» пройдёт твоё собеседование\.⚡* Представься, чтобы твою анкету нашли и с тобой пообщался нужный специалист\.
        ///
        ///Команда Directum подготовила список вакансий, которые могут тебе подойти\. Переходи [по ссылке](https://career.directum.ru/)\, а также подписывайся на нашу группу, чтобы первым узнавать об актуальной практике и новых вакансиях\..
        /// </summary>
        internal static string ThankYouInITAnother {
            get {
                return ResourceManager.GetString("ThankYouInITAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡*Спасибо\! Мы передадим твою анкету рекрутеру, в случае положительного решения он свяжется с тобой до 30 апреля ⏳\.*  Не забудь взять трубку с незнакомого номера, если указал телефон предпочтительным способом связи\. 
        ///
        ///Подписывайся на группу Студенты Directum по кнопке ниже\.⬇️ 
        ///
        ///Если остались вопросы, ты можешь пройти на сцену и узнать больше о практиках за столом «Практика в Directum»\.
        ///        .
        /// </summary>
        internal static string ThankYouPractice {
            get {
                return ResourceManager.GetString("ThankYouPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для начинающих айтишников мы подготовили формат группового общения с представителями направлений\. Узнай какой опыт нужно получить, чтобы устроиться к нам через время\.
        ///
        ///🔎*Ищи на сцене 4 больших стола Directum:*
        ///\-  Стол «Есть контакт \- разработка»\.
        ///\-  Стол «Есть контакт \- тестирование и инженерная поддержка»\.
        ///\-  Стол «Есть контакт \- аналитика и управление проектами»\.
        ///\-  Стол «Есть контакт \- маркетинг и продвижение»\.
        ///
        ///*Группе от 6 человек специалисты рассказывают  о своих направлениях\.*.
        /// </summary>
        internal static string TraineeITMan {
            get {
                return ResourceManager.GetString("TraineeITMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытые вакансии.
        /// </summary>
        internal static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚡*Поднимайся на сцену\. За столом с табличкой «Мы тебя ждали\. {0}» пройдёт твоё собеседование\.⚡* 
        ///Представься, чтобы твою анкету нашли и с тобой пообщался нужный специалист\.
        ///
        ///Команда Directum подготовила список вакансий, которые могут тебе подойти\. Переходи [по ссылке](https://career.directum.ru/)\, а также подписывайся на нашу группу, чтобы первым узнавать об актуальной практике и новых вакансиях\..
        /// </summary>
        internal static string WaitingForYou {
            get {
                return ResourceManager.GetString("WaitingForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cобеседование.
        /// </summary>
        internal static string WantInterview {
            get {
                return ResourceManager.GetString("WantInterview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попасть в IT.
        /// </summary>
        internal static string WantToIT {
            get {
                return ResourceManager.GetString("WantToIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На практику!.
        /// </summary>
        internal static string WantToPractice {
            get {
                return ResourceManager.GetString("WantToPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работал ли ты в IT\-компании или IT\-отделе?.
        /// </summary>
        internal static string WorkedInIT {
            get {
                return ResourceManager.GetString("WorkedInIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
