<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Apis.Sheets.v4" Version="1.67.0.3365" />
      <PackageReference Include="Telegram.Bot" Version="19.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BotCommon\BotCommon.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="BotMessages.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>BotMessages.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="BotMessages.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>BotMessages.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <None Update="Dockerfile">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Аналитика.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Есть контакт.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Системные инженеры.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Маркетинг.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Общая.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Попасть в IT.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Практика.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Разработка.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Тестирование.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Scenarios\Images\Писатели.jpg">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Scenarios\Images\" />
    </ItemGroup>

</Project>
